require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY);

const properties = [
  {
    host_name: 'Anna Gruber',
    property_name: 'Altbau-Juwel am Stephansplatz',
    address: 'Rotenturmstraße 12, 1010 Wien',
    checkin_time: '15:00',
    checkout_time: '11:00',
    floor_and_unit: '4. OG, Tür 8',
    checkin_instructions: 'Schlüsselbox am Hauseingang öffnen (Code unten). Aufzug zum 4. Stock, Tür 8 links. Bitte Schuhe im Eingangsbereich ausziehen.',
    wifi_name: 'Gruber_Gast_WLAN',
    wifi_password: 'Wien2024!Stephansdom',
    keybox_code: '2847',
    keybox_location: 'Rechts neben der Hauseingangstür, schwarze Box auf Augenhöhe',
    towels_bedding_info: 'Frische Handtücher im Badezimmerschrank (oberes Fach). Ersatzbettwäsche im Schlafzimmer-Kasten.',
    washing_machine_info: 'Waschmaschine im Badezimmer. Waschpulver im Schrank darunter. Programm "Pflegeleicht 30°C" empfohlen.',
    heating_ac_info: 'Fernwärme Wien — Thermostat im Flur. Stufe 3 = ca. 21°C. Bitte beim Verlassen auf 2 stellen.',
    trash_disposal_info: 'Restmüll (schwarz), Plastik (gelb), Papier (blau), Glas (weiß/bunt) — Müllraum im Erdgeschoss rechts.',
    household_appliances_info: 'Ceranfeld: Touch-Bedienung. Geschirrspüler: Tabs unter der Spüle. Kaffeemaschine: Nespresso (Kapseln in der Schublade).',
    nearest_public_transport: 'U1/U3 Stephansplatz, 3 Min. zu Fuß',
    nearest_supermarket: 'Billa Rotenturmstraße 23, Mo–Fr 7:15–19:30, Sa 7:15–18:00',
    restaurant_recommendations: 'Figlmüller (Schnitzel, Bäckerstraße), Lugeck (modern österreichisch), Trzesniewski (Brötchen, Dorotheergasse)',
    max_guests: '4',
    pets_allowed: 'Nein',
    smoking_allowed: 'Nein, auch nicht am Balkon',
    special_notes: 'Altbau — bitte die Haustür immer leise schließen. Ruhezeit 22:00–7:00.',
    house_rules: 'Nachtruhe ab 22 Uhr. Keine Partys. Müll bitte trennen. Fenster bei Regen schließen.',
    parking_info: 'Kurzparkzone 1. Bezirk (Mo–Fr 9–22 Uhr). Nächste Parkgarage: Parkgarage Am Hof, 5 Min.',
    emergency_contact: '+43 660 123 4001',
  },
  {
    host_name: 'Thomas Bauer',
    property_name: 'Prater-Loft mit Riesenrad-Blick',
    address: 'Praterstraße 38, 1020 Wien',
    checkin_time: '14:00',
    checkout_time: '10:00',
    floor_and_unit: '6. OG, Top 22',
    checkin_instructions: 'Schlüssel im KeyBox-Safe neben dem Briefkasten. Aufzug zum 6. Stock, dann links durch die Glastür.',
    wifi_name: 'PraterLoft_Guest',
    wifi_password: 'Riesenrad2024',
    keybox_code: '1956',
    keybox_location: 'Neben den Briefkästen im Eingangsbereich, silberne Box',
    towels_bedding_info: 'Handtücher im Bad am Haken. Extra Handtücher und Bettwäsche im Schlafzimmer-Kasten oben.',
    washing_machine_info: 'Waschtrockner im Abstellraum neben der Küche. Waschmittel auf dem Regal. Kurzprogramm 40°C für alles.',
    heating_ac_info: 'Klimaanlage mit Fernbedienung (liegt am Couchtisch). Heizung über Thermostat neben der Eingangstür.',
    trash_disposal_info: 'Mülltrennung: Restmüll, Plastik, Papier, Bio. Tonnen im Innenhof durch die Hintertür.',
    household_appliances_info: 'Induktionsherd (Töpfe müssen magnetisch sein). Geschirrspüler: Eco-Programm. Nespresso-Maschine auf der Anrichte.',
    nearest_public_transport: 'U1 Nestroyplatz, 2 Min. zu Fuß. Straßenbahn 2 (Praterstraße)',
    nearest_supermarket: 'Spar Praterstraße 42, Mo–Fr 7:00–20:00, Sa 7:00–18:00',
    restaurant_recommendations: 'Schweizerhaus (Stelze + Bier im Prater), Skopik & Lohn (Fine Dining), Café Ansari (Frühstück)',
    max_guests: '3',
    pets_allowed: 'Kleine Hunde erlaubt (max. 10 kg)',
    smoking_allowed: 'Nur am Balkon',
    special_notes: 'Vom Balkon aus sieht man das Riesenrad! Fernglas in der Schublade neben dem Sofa.',
    house_rules: 'Nachtruhe ab 22 Uhr. Balkon-Möbel bei Wind bitte reinnehmen. Schuhe ausziehen.',
    parking_info: 'Kurzparkzone 2. Bezirk (Mo–Fr 9–22 Uhr). Parkhaus Prater-Garage, Ausstellungsstraße 6.',
    emergency_contact: '+43 660 123 4002',
  },
  {
    host_name: 'Sarah Wimmer',
    property_name: 'Gemütliche Wohnung nahe Naschmarkt',
    address: 'Gumpendorfer Straße 19, 1060 Wien',
    checkin_time: '15:00',
    checkout_time: '11:00',
    floor_and_unit: '2. OG, Tür 5',
    checkin_instructions: 'Hauseingangscode: #3344. Treppe zum 2. Stock (kein Aufzug). Schlüssel in der Schlüsselbox neben Tür 5.',
    wifi_name: 'Wimmer_Naschmarkt',
    wifi_password: 'naschmarkt2024!',
    keybox_code: '7731',
    keybox_location: 'Direkt neben der Wohnungstür, kleine graue Box',
    towels_bedding_info: 'Handtücher und Waschlappen im Badezimmerregal. Extra Decke im Wohnzimmerschrank.',
    washing_machine_info: 'Keine Waschmaschine in der Wohnung. Nächster Waschsalon: Schnell & Sauber, Stumpergasse 4 (5 Min.).',
    heating_ac_info: 'Gasheizung — Thermostat in jedem Zimmer an der Wand. Keine Klimaanlage, aber Ventilator im Schlafzimmer.',
    trash_disposal_info: 'Alle Mülltonnen im Hof (Tür am Ende des Gangs im EG). Restmüll, Plastik, Papier, Glas.',
    household_appliances_info: 'Gasherd (Zünder links). Kein Geschirrspüler. Bialetti Mokka-Kanne auf dem Herd.',
    nearest_public_transport: 'U4 Kettenbrückengasse, 4 Min. zu Fuß',
    nearest_supermarket: 'Hofer Gumpendorfer Straße 25, Mo–Fr 7:40–20:00, Sa 7:40–18:00',
    restaurant_recommendations: 'Naschmarkt (5 Min., alles von Falafel bis Sushi), Café Drechsler (Frühstück), Umar Fisch (am Naschmarkt)',
    max_guests: '2',
    pets_allowed: 'Nein',
    smoking_allowed: 'Nein',
    special_notes: 'Altbau ohne Aufzug — 2. Stock, ca. 35 Stufen. Naschmarkt ist samstags am Flohmarkt-Tag besonders voll.',
    house_rules: 'Nachtruhe ab 22 Uhr. Kein Rauchen. Fenster im Bad nach dem Duschen öffnen (Schimmelgefahr).',
    parking_info: 'Kurzparkzone 6. Bezirk. Nächste Garage: Parkgarage Windmühlgasse, 3 Min.',
    emergency_contact: '+43 660 123 4003',
  },
  {
    host_name: 'Markus Steiner',
    property_name: 'Design-Apartment im Siebenten',
    address: 'Kirchengasse 41, 1070 Wien',
    checkin_time: '16:00',
    checkout_time: '11:00',
    floor_and_unit: '3. OG, Top 9',
    checkin_instructions: 'Smart-Lock an der Wohnungstür — Code wird per SMS geschickt. Aufzug vorhanden.',
    wifi_name: 'Steiner_Design7',
    wifi_password: 'Neubau7070!',
    keybox_code: '–',
    keybox_location: 'Kein Schlüssel nötig — Smart-Lock (Code per SMS)',
    towels_bedding_info: 'Hochwertige Handtücher im Bad. Bettwäsche aus Bio-Baumwolle. Ersatz im Einbauschrank im Flur.',
    washing_machine_info: 'Waschmaschine im Bad hinter der Schiebetür. Bio-Waschmittel daneben. Programm "Mix 30°C".',
    heating_ac_info: 'Fußbodenheizung mit Smart-Thermostat (App-Anleitung am Kühlschrank). Klimaanlage im Wohn- und Schlafzimmer.',
    trash_disposal_info: 'Mülltrennung im Küchenschrank unter der Spüle (3-fach Trennsystem). Müllraum im Keller.',
    household_appliances_info: 'Induktionsherd, Geschirrspüler (Tabs in Schublade), Kaffeevollautomat (Bohnen im Schrank links).',
    nearest_public_transport: 'U3 Neubaugasse, 3 Min. zu Fuß. Bus 13A (Kirchengasse)',
    nearest_supermarket: 'Billa Plus Neubaugasse 38, Mo–Fr 7:15–20:00, Sa 7:15–18:00',
    restaurant_recommendations: 'Amerlingbeisl (Innenhof, Stiftgasse), Maschu Maschu (israelisch), Café Jelinek (Wiener Kaffeehaus)',
    max_guests: '4',
    pets_allowed: 'Ja, nach Absprache',
    smoking_allowed: 'Nein',
    special_notes: 'Es gibt einen Innenhof-Garten — Zugang über die Hintertür in der Küche. Perfekt zum Frühstücken!',
    house_rules: 'Nachtruhe ab 22 Uhr. Smart-Lock schließt automatisch. Klimaanlage beim Verlassen bitte ausschalten.',
    parking_info: 'Kurzparkzone 7. Bezirk. Tiefgarage Museumsquartier, Museumsplatz 1 (10 Min.).',
    emergency_contact: '+43 660 123 4004',
  },
  {
    host_name: 'Elisabeth Moser',
    property_name: 'Charmante Josefstadt-Wohnung',
    address: 'Josefstädter Straße 56, 1080 Wien',
    checkin_time: '14:00',
    checkout_time: '10:30',
    floor_and_unit: '1. OG, Tür 3',
    checkin_instructions: 'Schlüssel bei der Nachbarin Frau Kovacs (Tür 4) abholen, falls niemand da ist → Schlüsselbox nutzen.',
    wifi_name: 'Moser_Josefstadt',
    wifi_password: 'Theater1080',
    keybox_code: '5528',
    keybox_location: 'Im Stiegenhaus, rechts neben dem Briefkasten, blaue Box',
    towels_bedding_info: 'Handtücher am Haken im Bad. Zusätzliche Sets im Schlafzimmerschrank (unteres Fach).',
    washing_machine_info: 'Waschmaschine im Abstellraum (Tür neben dem Bad). Waschmittel und Weichspüler daneben.',
    heating_ac_info: 'Zentralheizung — Thermostat im Wohnzimmer. Stufe 3–4 reicht im Winter. Keine Klimaanlage.',
    trash_disposal_info: 'Mülltonnen im Innenhof (Durchgang neben der Stiege). Bitte Kartons falten.',
    household_appliances_info: 'E-Herd mit Backrohr. Kein Geschirrspüler. Filterkaffeemaschine in der Küche.',
    nearest_public_transport: 'Straßenbahn 2 & 5 (Josefstädter Straße), U2 Rathaus 8 Min.',
    nearest_supermarket: 'Spar Josefstädter Straße 63, Mo–Fr 7:00–19:30, Sa 7:00–18:00',
    restaurant_recommendations: 'Piaristenkeller (traditionell, Piaristengasse), Café Hummel (Frühstück), Stomach (modern österreichisch)',
    max_guests: '3',
    pets_allowed: 'Katzen erlaubt, keine Hunde',
    smoking_allowed: 'Nein',
    special_notes: 'Das Theater in der Josefstadt ist 5 Min. entfernt — Abendkasse oft günstiger! Nachbarin Frau Kovacs spricht auch Englisch.',
    house_rules: 'Nachtruhe ab 22 Uhr. Haustür immer abschließen (2x drehen). Bitte kein Wasser in den Innenhof schütten.',
    parking_info: 'Kurzparkzone 8. Bezirk. Nächste Garage: Rathaus-Garage, Friedrich-Schmidt-Platz.',
    emergency_contact: '+43 660 123 4005',
  },
  {
    host_name: 'Daniel Hofer',
    property_name: 'Studentisches Loft am Alsergrund',
    address: 'Währinger Straße 18, 1090 Wien',
    checkin_time: '13:00',
    checkout_time: '11:00',
    floor_and_unit: '5. OG, Dachgeschoss rechts',
    checkin_instructions: 'Haustürcode: 1909#. Aufzug nur bis 4. OG, dann eine Treppe hoch. Schlüssel in der Box neben der Dachtür.',
    wifi_name: 'Hofer_DG_Alsergrund',
    wifi_password: 'UniWien2024',
    keybox_code: '3365',
    keybox_location: 'Neben der Dachgeschoss-Eingangstür, kleine schwarze Box',
    towels_bedding_info: 'Handtücher im Badezimmerregal. Nur ein Set pro Gast — bitte sparsam verwenden.',
    washing_machine_info: 'Gemeinschaftswaschküche im Keller (Münzautomat, 3€ pro Waschgang). Wäscheständer in der Wohnung.',
    heating_ac_info: 'Dachgeschoss wird im Sommer heiß! Ventilator im Schrank. Heizung: Thermostat neben der Tür.',
    trash_disposal_info: 'Müll bitte in die Tonnen vor dem Haus bringen (Restmüll, Plastik, Papier). Glascontainer um die Ecke.',
    household_appliances_info: 'Zwei-Platten-Herd, Minibackofen, Wasserkocher, French Press für Kaffee.',
    nearest_public_transport: 'U6 Währinger Straße–Volksoper, 1 Min. Straßenbahn 40/41/42.',
    nearest_supermarket: 'Billa Währinger Straße 26, Mo–Fr 7:15–20:00, Sa 7:15–18:00',
    restaurant_recommendations: 'Café Berg (Berggasse), Gasthaus Wickerl (Porzellangasse), Yamm! (vegetarisch, Uni-Nähe)',
    max_guests: '2',
    pets_allowed: 'Nein',
    smoking_allowed: 'Nur am Dachfenster mit offenem Fenster',
    special_notes: 'Dachschrägen — bitte Kopf einziehen beim Aufstehen im Bett! Perfekt für Uni-Besucher (Campus 5 Min.).',
    house_rules: 'Nachtruhe ab 22 Uhr. Dachfenster bei Regen unbedingt schließen! Aufzug fährt nur bis 4. OG.',
    parking_info: 'Kurzparkzone 9. Bezirk. Garage Votivpark, Universitätsstraße (10 Min.).',
    emergency_contact: '+43 660 123 4006',
  },
  {
    host_name: 'Fatima Yilmaz',
    property_name: 'Familienwohnung am Reumannplatz',
    address: 'Favoritenstraße 108, 1100 Wien',
    checkin_time: '14:00',
    checkout_time: '11:00',
    floor_and_unit: '2. OG, Tür 7',
    checkin_instructions: 'Schlüsselbox im Eingangsbereich (Code unten). Aufzug vorhanden. Willkommensmappe auf dem Küchentisch.',
    wifi_name: 'Yilmaz_Favoriten',
    wifi_password: 'favoriten100!',
    keybox_code: '8812',
    keybox_location: 'Links neben den Briefkästen, rote Box',
    towels_bedding_info: 'Handtücher im Bad auf der Ablage. Kinderbettwäsche im Schrank (Kinderzimmer). Extra Decken im Wohnzimmerschrank.',
    washing_machine_info: 'Waschmaschine in der Küche neben dem Kühlschrank. Waschpulver im Hängeschrank darüber. Trockner auch vorhanden.',
    heating_ac_info: 'Fernwärme Wien. Thermostate in jedem Zimmer. Stufe 3 = angenehm warm. Klimaanlage im Wohnzimmer.',
    trash_disposal_info: 'Müllraum im Keller (Schlüssel am Schlüsselbund, kleiner silberner). Alle Tonnen beschriftet.',
    household_appliances_info: 'Ceranfeld, Backrohr, Geschirrspüler, Mikrowelle. Kinderbesteck in der Schublade links.',
    nearest_public_transport: 'U1 Reumannplatz, 3 Min. zu Fuß. Bus 65A.',
    nearest_supermarket: 'Hofer Favoritenstraße 111, Mo–Fr 7:40–20:00, Sa 7:40–18:00',
    restaurant_recommendations: 'Kent (türkisch, Favoritenstraße), Pizzeria Osteria, Wienerberg City (Einkaufszentrum mit Food Court)',
    max_guests: '6',
    pets_allowed: 'Ja, Hunde und Katzen willkommen',
    smoking_allowed: 'Nur am Balkon',
    special_notes: 'Kinderbett und Hochstuhl vorhanden (Abstellraum). Spielplatz direkt gegenüber am Reumannplatz.',
    house_rules: 'Nachtruhe ab 22 Uhr. Haustiere bitte nicht auf die Couch. Balkonpflanzen gerne gießen!',
    parking_info: 'Gratis Parken (kein Kurzparkzone im 10. Bezirk). Garagenplatz auf Anfrage (15€/Nacht).',
    emergency_contact: '+43 660 123 4007',
  },
  {
    host_name: 'Peter Novak',
    property_name: 'Ruhige Gartenwohnung Meidling',
    address: 'Längenfeldgasse 12, 1120 Wien',
    checkin_time: '15:00',
    checkout_time: '10:00',
    floor_and_unit: 'Erdgeschoss, Tür 2 (Gartenseite)',
    checkin_instructions: 'Eingang über die Gartenseite (Durchgang links am Haus vorbei). Schlüssel in der Box neben der Terrassentür.',
    wifi_name: 'Novak_Garten12',
    wifi_password: 'Meidling2024',
    keybox_code: '4477',
    keybox_location: 'Neben der Terrassentür, grüne Schlüsselbox',
    towels_bedding_info: 'Handtücher im Badezimmerschrank. Garten-Handtücher (gestreift) auf der Terrasse nutzen.',
    washing_machine_info: 'Waschmaschine im Badezimmer. Bio-Waschmittel im Schrank. Wäsche kann im Garten aufgehängt werden.',
    heating_ac_info: 'Gasheizung mit Thermostat pro Zimmer. Im Sommer bleibt die EG-Wohnung angenehm kühl. Ventilator im Schrank.',
    trash_disposal_info: 'Mülltonnen im Vorgarten (schwarze Tonne = Restmüll, gelbe = Plastik). Papier und Glas zur Sammelstelle Ecke Längenfeldgasse.',
    household_appliances_info: 'Gasherd (4 Flammen), Backrohr, Geschirrspüler. Gartengrill auf der Terrasse (Holzkohle im Schuppen).',
    nearest_public_transport: 'U4/U6 Längenfeldgasse, 2 Min. zu Fuß',
    nearest_supermarket: 'Spar Längenfeldgasse 18, Mo–Fr 7:00–19:30, Sa 7:00–18:00',
    restaurant_recommendations: 'Gasthaus Quell (Wiener Küche, Reindorfgasse), Pizzeria Riva, Café Ritter (Frühstück, Ottakringer Str.)',
    max_guests: '4',
    pets_allowed: 'Ja, eingezäunter Garten vorhanden',
    smoking_allowed: 'Nur im Garten',
    special_notes: 'Garten-Wohnung mit eigener Terrasse! Grill darf genutzt werden. Bitte abends Terrassentür abschließen.',
    house_rules: 'Nachtruhe ab 22 Uhr (Garten ab 21 Uhr). Grill nach Benutzung reinigen. Gartentor schließen (Katzen der Nachbarn).',
    parking_info: 'Gratis Parken direkt vor dem Haus (kein Kurzparkzone). Eigener Stellplatz im Hof auf Anfrage.',
    emergency_contact: '+43 660 123 4008',
  },
  {
    host_name: 'Maria Schönberg',
    property_name: 'Villa-Apartment Hietzing',
    address: 'Hietzinger Hauptstraße 22, 1130 Wien',
    checkin_time: '16:00',
    checkout_time: '11:00',
    floor_and_unit: '1. OG, linke Seite',
    checkin_instructions: 'Gartentor-Code: 1130#. Eingang über die Freitreppe zum 1. OG. Schlüssel in der Box neben der Eingangstür.',
    wifi_name: 'Schoenb_Villa13',
    wifi_password: 'Schoenbrunn1!',
    keybox_code: '6143',
    keybox_location: 'Rechts neben der Eingangstür im 1. OG, Messingbox',
    towels_bedding_info: 'Hochwertige Frottee-Handtücher im Badezimmer. Bademantel im Schrank. Ersatzbettwäsche im Flurschrank.',
    washing_machine_info: 'Waschmaschine und Trockner in der Waschküche im Keller (Schlüssel am Bund). Premium-Waschmittel vorhanden.',
    heating_ac_info: 'Zentralheizung mit Fußbodenheizung im Bad. Klimaanlage in allen Räumen (Fernbedienung auf dem Nachttisch).',
    trash_disposal_info: 'Mülltonnen hinter dem Haus (Gartenweg links). Kompost im Garten (grüne Tonne).',
    household_appliances_info: 'Gasherd (Miele), Geschirrspüler, Kaffeevollautomat (De\'Longhi), Wasserkocher, Toaster.',
    nearest_public_transport: 'U4 Hietzing, 5 Min. zu Fuß. Straßenbahn 60.',
    nearest_supermarket: 'Billa Plus Hietzinger Hauptstraße 30, Mo–Fr 7:15–20:00, Sa 7:15–18:00',
    restaurant_recommendations: 'Plachutta Hietzing (Tafelspitz), Café Dommayer (Kaffeehaus-Klassiker), Brandauers Bierbögen (Schönbrunn)',
    max_guests: '5',
    pets_allowed: 'Kleine Hunde erlaubt, nicht im Garten (Igel!)',
    smoking_allowed: 'Nur im Garten',
    special_notes: 'Schloss Schönbrunn ist 10 Min. zu Fuß! Tiergarten-Eingang ebenfalls in der Nähe. Garten darf genutzt werden.',
    house_rules: 'Nachtruhe ab 22 Uhr. Gartentor immer schließen. Bitte keine Gartenmöbel umstellen. Villa ist denkmalgeschützt.',
    parking_info: 'Eigener Parkplatz im Hof (Einfahrt über Seitengasse). Gratis Parken in der Straße.',
    emergency_contact: '+43 660 123 4009',
  },
  {
    host_name: 'Georg Winkler',
    property_name: 'Penzing Hideaway mit Wienerwaldblick',
    address: 'Hütteldorfer Straße 130, 1140 Wien',
    checkin_time: '15:00',
    checkout_time: '10:00',
    floor_and_unit: '4. OG, Tür 14',
    checkin_instructions: 'Eingangscode Haustür: 5577. Aufzug zum 4. Stock. Schlüsselbox neben Tür 14.',
    wifi_name: 'Winkler_Penzing14',
    wifi_password: 'Wienerwald2024',
    keybox_code: '9034',
    keybox_location: 'Links neben der Wohnungstür, kleine weiße Box',
    towels_bedding_info: 'Handtücher im Badschrank (Fach 2). Strandtücher für den Sommer im Flurschrank.',
    washing_machine_info: 'Waschmaschine im Bad. Waschpulver im Hängeschrank. 40°C-Programm für alles.',
    heating_ac_info: 'Fernwärme mit Thermostat in jedem Raum. Keine Klimaanlage — dafür kühle Brise vom Wienerwald.',
    trash_disposal_info: 'Müllraum im Erdgeschoss links. Alle Tonnen vorhanden. Biomüll-Tonne ist die braune.',
    household_appliances_info: 'E-Herd, Backrohr, Mikrowelle, Geschirrspüler. Moka-Kanne und Filterkaffee vorhanden.',
    nearest_public_transport: 'U3 Hütteldorfer Straße, 4 Min. zu Fuß. S45 Penzing.',
    nearest_supermarket: 'Hofer Hütteldorfer Straße 140, Mo–Fr 7:40–20:00, Sa 7:40–18:00',
    restaurant_recommendations: 'Heuriger 10er Marie (Ottakring, Weingarten), Gasthaus Grünspan (Hütteldorf), Café Carina (Live-Musik)',
    max_guests: '3',
    pets_allowed: 'Nein',
    smoking_allowed: 'Nur am Balkon',
    special_notes: 'Wanderweg in den Wienerwald startet 10 Min. entfernt! Fernglas auf dem Balkon. Sonnenuntergang-View Richtung Westen.',
    house_rules: 'Nachtruhe ab 22 Uhr. Balkontür bei Sturm schließen. Bitte kein Grillen am Balkon.',
    parking_info: 'Gratis Parken (14. Bezirk keine Kurzparkzone). Stellplatz direkt vor dem Haus oft frei.',
    emergency_contact: '+43 660 123 4010',
  },
  {
    host_name: 'Lisa Berger',
    property_name: 'Kreativ-WG in Ottakring',
    address: 'Thaliastraße 85, 1160 Wien',
    checkin_time: '14:00',
    checkout_time: '11:00',
    floor_and_unit: '3. OG, Tür 11',
    checkin_instructions: 'Haustür ist tagsüber offen (8–20 Uhr). Danach Klingel "Berger" drücken oder Schlüsselbox nutzen. Kein Aufzug.',
    wifi_name: 'Berger_Kreativ16',
    wifi_password: 'Ottakring1610!',
    keybox_code: '2290',
    keybox_location: 'Im Stiegenhaus, 3. OG, rechts neben Tür 11, schwarze Box',
    towels_bedding_info: 'Bunte Handtücher im Badregal. Bettwäsche aus Leinen. Extra-Decken im Flur oben im Schrank.',
    washing_machine_info: 'Waschmaschine in der Küche. Öko-Waschmittel daneben. Bitte nur volle Maschinen waschen.',
    heating_ac_info: 'Gasheizung (Gastherme im Bad). Thermostat im Wohnzimmer. Keine Klimaanlage, Ventilator vorhanden.',
    trash_disposal_info: 'Müllinseln direkt vor dem Haus. Restmüll, Plastik, Papier, Glas. Biomüll: Kompost im Innenhof.',
    household_appliances_info: 'Gasherd, kein Geschirrspüler, Wasserkocher, Handfilter für Kaffee (Bohnen im Kühlschrank).',
    nearest_public_transport: 'Straßenbahn 46 (Thaliastraße). U3 Ottakring 8 Min.',
    nearest_supermarket: 'Billa Thaliastraße 90, Mo–Fr 7:15–19:30, Sa 7:15–18:00',
    restaurant_recommendations: 'Café Carina (Live-Musik), Kent (türkische Küche, Brunnenmarkt), Die Schöne (Brunch), Brunnenmarkt (täglich frisch)',
    max_guests: '2',
    pets_allowed: 'Ja, alle Tiere willkommen',
    smoking_allowed: 'Nur in der Küche bei offenem Fenster',
    special_notes: 'Der Brunnenmarkt ist Wiens längster Straßenmarkt — 5 Min. entfernt! Am Samstag unbedingt den Bauernmarkt am Yppenplatz besuchen.',
    house_rules: 'Nachtruhe ab 23 Uhr (Ottakring ist entspannt). 3. OG ohne Aufzug. Gastherme NIE ausschalten.',
    parking_info: 'Gratis Parken (16. Bezirk keine Kurzparkzone). Fahrräder im Innenhof abstellen.',
    emergency_contact: '+43 660 123 4011',
  },
  {
    host_name: 'Christine Lehner',
    property_name: 'Elegantes Währinger Cottage',
    address: 'Cottagegasse 28, 1180 Wien',
    checkin_time: '15:00',
    checkout_time: '10:00',
    floor_and_unit: 'Erdgeschoss (eigener Eingang)',
    checkin_instructions: 'Gartentor öffnen (nicht abgesperrt). Eigener Eingang links am Haus. Schlüssel in der Box neben der Tür.',
    wifi_name: 'Lehner_Cottage18',
    wifi_password: 'Waehring1818!',
    keybox_code: '7765',
    keybox_location: 'Neben der Eingangstür, unter dem Briefkasten, silberne Box',
    towels_bedding_info: 'Flauschige Handtücher im Bad. Bademantel hinter der Badtür. Extra Bettwäsche im Schlafzimmer-Schrank oben.',
    washing_machine_info: 'Waschmaschine im Hauswirtschaftsraum (Tür neben der Küche). Waschmittel, Weichspüler, Trockner vorhanden.',
    heating_ac_info: 'Zentralheizung mit Einzelraumregelung. Kamin im Wohnzimmer (Holz im Schuppen, bitte nur abends nutzen).',
    trash_disposal_info: 'Mülltonnen im Vorgarten hinter der Hecke. Bio, Restmüll, Plastik, Papier, Glas alle vorhanden.',
    household_appliances_info: 'Vollausgestattete Küche: E-Herd, Backrohr, Geschirrspüler, Kaffeevollautomat, Toaster, Entsafter.',
    nearest_public_transport: 'Straßenbahn 41 (Pötzleinsdorfer Straße), 3 Min. U6 Währinger Straße 12 Min.',
    nearest_supermarket: 'Spar Gourmet Währinger Straße 122, Mo–Fr 7:00–20:00, Sa 7:00–18:00',
    restaurant_recommendations: 'Heuriger Zimmermann (Pötzleinsdorf, eigener Wein), Café Weimar (Kaffeehaus), Gasthaus Zur Stadt Paris (Josefstädter Str.)',
    max_guests: '4',
    pets_allowed: 'Ja, eingezäunter Garten',
    smoking_allowed: 'Nur im Garten',
    special_notes: 'Das Cottage-Viertel ist Wiens grünstes Wohngebiet! Türkenschanzpark 5 Min. zu Fuß. Kamin-Holz bitte nur aus dem Schuppen nehmen.',
    house_rules: 'Nachtruhe ab 22 Uhr. Gartentor abends schließen. Kamin nur mit Funkenschutzgitter nutzen. Schuhe bitte ausziehen.',
    parking_info: 'Eigener Stellplatz in der Einfahrt. Gratis Parken in der Straße (18. Bezirk keine Kurzparkzone).',
    emergency_contact: '+43 660 123 4012',
  },
];

async function seed() {
  console.log(`Seeding ${properties.length} properties...\n`);

  for (const property of properties) {
    const { data, error } = await supabase
      .from('properties')
      .insert([property])
      .select('id, property_name')
      .single();

    if (error) {
      console.error(`✗ ${property.property_name}: ${error.message}`);
    } else {
      console.log(`✓ ${data.property_name} (${data.id})`);
    }
  }

  console.log('\nDone.');
}

seed();
